version: '3'

networks: 
    appjs:

services: 
    app:
        build: 
            context: .
            target: dev
        volumes: 
            - "./app:/src"
        ports: 
            - "8080:8080"
        command: npm run start:dev
        environment:
            NODE_ENV: development
        networks: 
            - appjs
    